name: slam ci

on:
  pull_request:
    branches: [ '**' ]
  push:
    branches: [ '**' ]

jobs:
  test_melodic:
    name: Build and Test ROS melodic package
    runs-on: ubuntu-18.04
    steps:
      - uses: ros-tooling/setup-ros@v0.1
        with:
          required-ros-distributions: melodic
      - uses: ros-tooling/action-ros-ci@v0.1
        with:
          package-name: my_package
          target-ros1-distro: melodic
  test_noetic:
    name: Build and Test ROS Noetic package
    runs-on: ubuntu-20.04
    steps:
      - uses: ros-tooling/setup-ros@v0.1
        with:
          required-ros-distributions: noetic
      - uses: ros-tooling/action-ros-ci@v0.1
        with:
          package-name: slam
          target-ros1-distro: noetic
      - name: Run tests
        run: catkin_make -j8 run_tests_slam