name: slam ci

on:
  pull_request:
    branches: [ '**' ]
  push:
    branches: [ '**' ]

jobs:
  test:
    name: Build and Test ROS package
      - uses: ros-tooling/setup-ros@v0.1
        with:
          required-ros-distributions: noetic
      - uses: ros-tooling/action-ros-ci@v0.1
        with:
          package-name: slam
          target-ros1-distro: noetic
      - name: Run tests
        run: catkin_make -j8 run_tests_slam